// Post action types
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST = 'FETCH_POST';
export const RESET_POST = 'RESET_POST';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_POSTS_BY_CATEGORY_ID = 'FETCH_POSTS_BY_CATEGORY_ID';
export const RESET_CATEGORY_POSTS = 'RESET_CATEGORY_POSTS';